// TODO: convert this to a CSV

// Various syntactic elements and their unicode equivalents
def_eq:           $ => choice('==', '≜'),
set_in:           $ => choice('\\in', '∈'),
gets:             $ => choice('<-', '⟵'),
forall:           $ => choice('\\A', '\\forall', '∀'),
exists:           $ => choice('\\E', '\\exists', '∃'),
temporal_forall:  $ => choice('\\AA'),
temporal_exists:  $ => choice('\\EE'),
all_map_to:       $ => choice('|->', '⟼'), 
maps_to:          $ => choice('->', '⟶'),
langle_bracket:   $ => choice('<<', '〈'),
rangle_bracket:   $ => choice('>>', '〉'),
case_box:         $ => choice('[]', '□'),
case_arrow:       $ => choice('->', '⟶'),
bullet_conj:      $ => choice('/\\', '∧'),
bullet_disj:      $ => choice('\\/', '∨'),

// Prefix operator symbols and their unicode equivalents
lnot:             $ => choice('\\lnot', '\\neg', '~', '¬'),
union:            $ => 'UNION',
subset:           $ => 'SUBSET',
domain:           $ => 'DOMAIN',
negative:         $ => '-',
enabled:          $ => 'ENABLED',
unchanged:        $ => 'UNCHANGED',
always:           $ => choice('[]', '□'),
eventually:       $ => choice('<>', '⋄'),

// Infix operator symbols and their unicode equivalents
implies:          $ => choice('=>', '⟹'),
plus_arrow:       $ => choice('-+->', '⇸'),
equiv:            $ => choice('\\equiv', '≡'),
iff:              $ => choice('<=>', '⟺'),
leads_to:         $ => choice('~>', '⇝'),
land:             $ => choice('/\\', '\\land', '∧'),
lor:              $ => choice('\\/', '\\lor', '∨'),
assign:           $ => choice(':=', '≔'),
bnf_rule:         $ => choice('::=', '⩴'),
eq:               $ => '=',
neq:              $ => choice('/=', '#', '≠'),
lt:               $ => '<',
gt:               $ => '>',
leq:              $ => choice('<=', '\\leq', '≤'),
geq:              $ => choice('>=', '\\geq', '≥'),
approx:           $ => choice('\\approx', '≈'),
rs_ttile:         $ => choice('|-', '⊢'),
rd_ttile:         $ => choice('|=', '⊨'),
ls_ttile:         $ => choice('-|', '⊣'),
ld_ttile:         $ => choice('=|', '⫤'),
asymp:            $ => choice('\\asymp', '≍'),
cong:             $ => choice('\\cong', '≅'),
doteq:            $ => choice('\\doteq', '≐'),
gg:               $ => choice('\\gg', '≫'),
ll:               $ => choice('\\ll', '≪'),
in:               $ => choice('\\in', '∈'),
notin:            $ => choice('\\notin', '∉'),
prec:             $ => choice('\\prec', '≺'),
succ:             $ => choice('\\succ', '≻'),
preceq:           $ => choice('\\preceq', '⪯'),
succeq:           $ => choice('\\succeq', '⪰'),
propto:           $ => choice('\\propto', '∝'),
sim:              $ => choice('\\sim', '∼'),
simeq:            $ => choice('\\simeq', '≃'),
sqsubset:         $ => choice('\\sqsubset', '⊏'),
sqsupset:         $ => choice('\\sqsupset', '⊐'),
sqsubseteq:       $ => choice('\\sqsubseteq', '⊑'),
sqsupseteq:       $ => choice('\\sqsupseteq', '⊒'),
subset:           $ => choice('\\subset', '⊂'),
supset:           $ => choice('\\supset', '⊃'),
subseteq:         $ => choice('\\subseteq', '⊆'),
supseteq:         $ => choice('\\supseteq', '⊇'),
compose:          $ => '@@',
map_to:           $ => ':>',
map_from:         $ => '<:',
setminus:         $ => '\\',
cap:              $ => choice('\\cap', '∩'),
cup:              $ => choice('\\cup', '∪'),
dots_2:           $ => choice('..', '‥'),
dots_3:           $ => choice('...', '…'),
plus:             $ => '+',
plusplus:         $ => '++',
oplus:            $ => choice('\\oplus', '⊕'),
ominus:           $ => choice('\\ominus', '⊖'),
mod:              $ => '%',
modmod:           $ => '%%',
vert:             $ => '|',
vertvert:         $ => choice('||', '‖'),
minus:            $ => '-',
minusminus:       $ => '--',
amp:              $ => '&',
ampamp:           $ => '&&',
odot:             $ => choice('\\odot', '⊙'),
oslash:           $ => choice('\\oslash', '⊘'),
otimes:           $ => choice('\\otimes', '⊗'),
mul:              $ => '*',
mulmul:           $ => '**',
slash:            $ => '/',
slashslash:       $ => '//',
bigcirc:          $ => choice('\\bigcirc', '◯'),
bullet:           $ => choice('\\bullet', '●'),
div:              $ => choice('\\div', '÷'),
circ:             $ => choice('\\circ', '∘'),
star:             $ => choice('\\star', '⋆'),
excl:             $ => choice('!!', '‼'),
qq:               $ => choice('??', '⁇'),
hashhash:         $ => '##',
dol:              $ => '$',
doldol:           $ => '$$',
sqcap:            $ => choice('\\sqcap', '⊓'),
sqcup:            $ => choice('\\sqcup', '⊔'),
uplus:            $ => choice('\\uplus', '⊎'),
times:            $ => choice('\\X', '\\times', '×'),
wr:               $ => choice('\\wr', '≀'),
cdot:             $ => choice('\\cdot', '⋅'),
pow:              $ => '^',
powpow:           $ => '^^',
rfield:           $ => '.',

// Postfix operator symbols and their unicode equivalents
sup_plus:         $ => choice('^+', '⁺'),
asterisk:         $ => '^*',
sup_hash:         $ => '^#',
prime:            $ => '\'',